### ISSUE TITLE
Redesign header,footer and side bar 

### ISSUE THREAD

**Issue by UdaySagar-Git** [UdaySagar-Git/studysphere#21]
![image](https://github.com/UdaySagar-Git/studysphere/assets/111575806/950e97c8-4eb1-411b-8fb6-ca553af0a9c2)

remove toggle icon completely in desktop view or move it somewhere to bottom 

`x` icon is not looking good with logo just beside it

side bar can be improved a lot 
may be getting rid of gray border 
having some rounded fill for active 

eg :

![image](https://github.com/UdaySagar-Git/studysphere/assets/111575806/974049ce-c56e-44b0-8227-eaa04de90d4d)

for footer 
just some thing like this is enough 
we dont need complete footer with all social media 

![image](https://github.com/UdaySagar-Git/studysphere/assets/111575806/63d32303-0111-4246-8548-35d8c99697d4)

just include copyright along with githublink with very light background and grayish text

**Comment by UdaySagar-Git** [comment]
@goutham4126

**Comment by goutham4126** [comment]
👍  @UdaySagar-Git
